[package]
name = "elfy"
version = "0.1.4"
authors = ["JerTH <jeremyhatcher27@gmail.com>"]
edition = "2018"
license = "MIT"
description = """
Executable Linkable Format file parser
"""
keywords = ["ELF", "unix", "arm"]

homepage = "https://github.com/JerTH/elfy"
documentation = "https://github.com/JerTH/elfy"
repository = "https://github.com/JerTH/elfy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
