[package]
name = "elfy"
version = "0.1.0"
authors = ["Jeremy T Hatcher <jeremyhatcher27@gmail.com>"]
edition = "2018"
license = "MIT"
description = "ELF file parser"
homepage = "https://github.com/JerTH/elfy"
documentation = "https://github.com/JerTH/elfy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
